#!/usr/bin/env python3
import asyncio
import sys
import os
from datetime import datetime
from motor.motor_asyncio import AsyncIOMotorClient
from bson import ObjectId
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# MongoDB bağlantısı - .env dosyasından al
MONGO_URI = os.getenv("MONGO_URI")
if not MONGO_URI:
    raise ValueError("MONGO_URI environment variable not found!")

# Database name'i URI'dan extract et
if "/" in MONGO_URI:
    DATABASE_NAME = MONGO_URI.split("/")[-1].split("?")[0]
else:
    DATABASE_NAME = "netflix_clone_db"

COLLECTION_NAME = "contents"

# 25 film verisi
movies_data = [
    {
        "title": "The Shawshank Redemption",
        "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "release_date": "1994-09-23",
        "duration": "142 min",
        "rating": 9.3,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=6hB3S9bIaco",
        "trailer_url": "https://www.youtube.com/watch?v=6hB3S9bIaco",
        "starring": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        "director": "Frank Darabont",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "crime"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": False
    },
    {
        "title": "The Godfather",
        "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "release_date": "1972-03-24",
        "duration": "175 min",
        "rating": 9.2,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=sY1S34973zA",
        "trailer_url": "https://www.youtube.com/watch?v=sY1S34973zA",
        "starring": ["Marlon Brando", "Al Pacino", "James Caan"],
        "director": "Francis Ford Coppola",
        "language": "English",
        "country": "USA",
        "tags": ["crime", "drama"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": False
    },
    {
        "title": "The Dark Knight",
        "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "release_date": "2008-07-18",
        "duration": "152 min",
        "rating": 9.0,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        "trailer_url": "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        "starring": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        "director": "Christopher Nolan",
        "language": "English",
        "country": "USA",
        "tags": ["action", "crime", "drama"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": True
    },
    {
        "title": "Pulp Fiction",
        "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "release_date": "1994-10-14",
        "duration": "154 min",
        "rating": 8.9,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
        "trailer_url": "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
        "starring": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        "director": "Quentin Tarantino",
        "language": "English",
        "country": "USA",
        "tags": ["crime", "drama"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": True
    },
    {
        "title": "The Lord of the Rings: The Return of the King",
        "description": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        "release_date": "2003-12-17",
        "duration": "201 min",
        "rating": 8.9,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWI5MTktXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWI5MTktXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
        "trailer_url": "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
        "starring": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        "director": "Peter Jackson",
        "language": "English",
        "country": "New Zealand",
        "tags": ["adventure", "drama", "fantasy"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": False
    },
    {
        "title": "Fight Club",
        "description": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        "release_date": "1999-10-15",
        "duration": "139 min",
        "rating": 8.8,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=qtRKdVHc-cE",
        "trailer_url": "https://www.youtube.com/watch?v=qtRKdVHc-cE",
        "starring": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        "director": "David Fincher",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "thriller"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": True
    },
    {
        "title": "Forrest Gump",
        "description": "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
        "release_date": "1994-07-06",
        "duration": "142 min",
        "rating": 8.8,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=bLvqoHBptjg",
        "trailer_url": "https://www.youtube.com/watch?v=bLvqoHBptjg",
        "starring": ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        "director": "Robert Zemeckis",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "romance"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": False
    },
    {
        "title": "Inception",
        "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "release_date": "2010-07-16",
        "duration": "148 min",
        "rating": 8.8,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=YoHD9XEInc0",
        "trailer_url": "https://www.youtube.com/watch?v=YoHD9XEInc0",
        "starring": ["Leonardo DiCaprio", "Marion Cotillard", "Tom Hardy"],
        "director": "Christopher Nolan",
        "language": "English",
        "country": "USA",
        "tags": ["action", "adventure", "sci-fi"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": True
    },
    {
        "title": "The Matrix",
        "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        "release_date": "1999-03-31",
        "duration": "136 min",
        "rating": 8.7,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=vKQi3bBA1y8",
        "trailer_url": "https://www.youtube.com/watch?v=vKQi3bBA1y8",
        "starring": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        "director": "The Wachowskis",
        "language": "English",
        "country": "USA",
        "tags": ["action", "sci-fi"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": True
    },
    {
        "title": "Goodfellas",
        "description": "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
        "release_date": "1990-09-21",
        "duration": "146 min",
        "rating": 8.7,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
        "trailer_url": "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
        "starring": ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
        "director": "Martin Scorsese",
        "language": "English",
        "country": "USA",
        "tags": ["biography", "crime", "drama"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Interstellar",
        "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "release_date": "2014-11-07",
        "duration": "169 min",
        "rating": 8.6,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=zSWdZVtXT7E",
        "trailer_url": "https://www.youtube.com/watch?v=zSWdZVtXT7E",
        "starring": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        "director": "Christopher Nolan",
        "language": "English",
        "country": "USA",
        "tags": ["adventure", "drama", "sci-fi"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": False
    },
    {
        "title": "Parasite",
        "description": "A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals.",
        "release_date": "2019-10-11",
        "duration": "132 min",
        "rating": 8.6,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=5xH0HfJHsaY",
        "trailer_url": "https://www.youtube.com/watch?v=5xH0HfJHsaY",
        "starring": ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Cho"],
        "director": "Bong Joon Ho",
        "language": "Korean",
        "country": "South Korea",
        "tags": ["comedy", "drama", "thriller"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": True
    },
    {
        "title": "The Silence of the Lambs",
        "description": "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
        "release_date": "1991-02-14",
        "duration": "118 min",
        "rating": 8.6,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
        "trailer_url": "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
        "starring": ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
        "director": "Jonathan Demme",
        "language": "English",
        "country": "USA",
        "tags": ["crime", "drama", "thriller"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Avengers: Endgame",
        "description": "After the devastating events of Avengers: Infinity War, the universe is in ruins. The remaining Avengers assemble once more.",
        "release_date": "2019-04-26",
        "duration": "181 min",
        "rating": 8.4,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=TcMBFSGVi1c",
        "trailer_url": "https://www.youtube.com/watch?v=TcMBFSGVi1c",
        "starring": ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
        "director": "Anthony Russo, Joe Russo",
        "language": "English",
        "country": "USA",
        "tags": ["action", "adventure", "drama"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": True
    },
    {
        "title": "Spirited Away",
        "description": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
        "release_date": "2001-07-20",
        "duration": "125 min",
        "rating": 8.6,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=ByXuk9QqQkk",
        "trailer_url": "https://www.youtube.com/watch?v=ByXuk9QqQkk",
        "starring": ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"],
        "director": "Hayao Miyazaki",
        "language": "Japanese",
        "country": "Japan",
        "tags": ["animation", "adventure", "family"],
        "content_type": "MOVIE",
        "featured": True,
        "trending": False
    },
    {
        "title": "Casablanca",
        "description": "A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.",
        "release_date": "1942-11-26",
        "duration": "102 min",
        "rating": 8.5,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=BkL9l7qovsE",
        "trailer_url": "https://www.youtube.com/watch?v=BkL9l7qovsE",
        "starring": ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"],
        "director": "Michael Curtiz",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "romance", "war"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "The Departed",
        "description": "An undercover cop and a police informant play a cat and mouse game with each other as they infiltrate an Irish gang in South Boston.",
        "release_date": "2006-10-06",
        "duration": "151 min",
        "rating": 8.5,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=SGWvwjZ0eDc",
        "trailer_url": "https://www.youtube.com/watch?v=SGWvwjZ0eDc",
        "starring": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
        "director": "Martin Scorsese",
        "language": "English",
        "country": "USA",
        "tags": ["crime", "drama", "thriller"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Seven",
        "description": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        "release_date": "1995-09-22",
        "duration": "127 min",
        "rating": 8.6,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=znmZoVkCjpI",
        "trailer_url": "https://www.youtube.com/watch?v=znmZoVkCjpI",
        "starring": ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"],
        "director": "David Fincher",
        "language": "English",
        "country": "USA",
        "tags": ["crime", "drama", "mystery"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "The Prestige",
        "description": "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        "release_date": "2006-10-20",
        "duration": "130 min",
        "rating": 8.5,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=o4gHCmTQDVI",
        "trailer_url": "https://www.youtube.com/watch?v=o4gHCmTQDVI",
        "starring": ["Hugh Jackman", "Christian Bale", "Michael Caine"],
        "director": "Christopher Nolan",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "mystery", "thriller"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Gladiator",
        "description": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        "release_date": "2000-05-05",
        "duration": "155 min",
        "rating": 8.5,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=owK1qxDselE",
        "trailer_url": "https://www.youtube.com/watch?v=owK1qxDselE",
        "starring": ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
        "director": "Ridley Scott",
        "language": "English",
        "country": "USA",
        "tags": ["action", "adventure", "drama"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Whiplash",
        "description": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        "release_date": "2014-10-10",
        "duration": "106 min",
        "rating": 8.5,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=7d_jQycdKGo",
        "trailer_url": "https://www.youtube.com/watch?v=7d_jQycdKGo",
        "starring": ["Miles Teller", "J.K. Simmons", "Paul Reiser"],
        "director": "Damien Chazelle",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "music"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": True
    },
    {
        "title": "The Green Mile",
        "description": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        "release_date": "1999-12-10",
        "duration": "189 min",
        "rating": 8.6,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=Ki4haFrqSrw",
        "trailer_url": "https://www.youtube.com/watch?v=Ki4haFrqSrw",
        "starring": ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
        "director": "Frank Darabont",
        "language": "English",
        "country": "USA",
        "tags": ["crime", "drama", "fantasy"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Shutter Island",
        "description": "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
        "release_date": "2010-02-19",
        "duration": "138 min",
        "rating": 8.2,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDUtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDUtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=v8yrZSkKxTA",
        "trailer_url": "https://www.youtube.com/watch?v=v8yrZSkKxTA",
        "starring": ["Leonardo DiCaprio", "Emily Mortimer", "Mark Ruffalo"],
        "director": "Martin Scorsese",
        "language": "English",
        "country": "USA",
        "tags": ["mystery", "thriller"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Django Unchained",
        "description": "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        "release_date": "2012-12-25",
        "duration": "165 min",
        "rating": 8.4,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=_iH0UBYDI4g",
        "trailer_url": "https://www.youtube.com/watch?v=_iH0UBYDI4g",
        "starring": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
        "director": "Quentin Tarantino",
        "language": "English",
        "country": "USA",
        "tags": ["drama", "western"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    },
    {
        "title": "Memento",
        "description": "A man with short-term memory loss attempts to track down his wife's murderer.",
        "release_date": "2000-10-11",
        "duration": "113 min",
        "rating": 8.4,
        "cover_image_url": "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "thumbnail_url": "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "video_url": "https://www.youtube.com/watch?v=4CV41hoyS8A",
        "trailer_url": "https://www.youtube.com/watch?v=4CV41hoyS8A",
        "starring": ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
        "director": "Christopher Nolan",
        "language": "English",
        "country": "USA",
        "tags": ["mystery", "thriller"],
        "content_type": "MOVIE",
        "featured": False,
        "trending": False
    }
]

async def create_movies():
    client = AsyncIOMotorClient(MONGO_URI)
    db = client[DATABASE_NAME]
    collection = db[COLLECTION_NAME]
    
    # Her film için zaman damgası ekle
    current_time = datetime.utcnow()
    for movie in movies_data:
        movie['time_created'] = current_time
    
    # Filmleri toplu olarak ekle
    result = await collection.insert_many(movies_data)
    
    print(f"✅ {len(result.inserted_ids)} film başarıyla eklendi!")
    print(f"📊 Eklenen film ID'leri: {result.inserted_ids}")
    
    # Veritabanını kapat
    client.close()

if __name__ == "__main__":
    asyncio.run(create_movies())